import { Metadata } from "next";
import MovieVideo from "../../../../components/movie-videos";
import MovieInfo from "../../../../components/movie-info";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Movie",
  description: "Generated by Next.js",
};

export default async function MovieDetail({
  params: { id },
}: {
  params: { id: string };
}) {
  console.log(id)
  return (
    <div>
      <h3>Movie Detail page</h3>
      <Suspense fallback={<h1>Loading...</h1>}>
        {/* @ts-expect-error Async Server Component */}
        <MovieVideo id={id} />
      </Suspense>
      <Suspense fallback={<h1>Loading...</h1>}>
        {/* @ts-expect-error Async Server Component */}
        <MovieInfo id={id} />
      </Suspense>
    </div>
  );
}
