import { Metadata } from "next";
import MovieVideo from "../../../../components/MovieVideo";
import MovieInfo, { getMovie } from "../../../../components/MovieInfo";
import { Suspense } from "react";

// 아래 generateMetadata()로 메타데이터 선언했기 때문에 필요 없음
// export const metadata: Metadata = {
//   title: "Movie",
//   description: "Generated by Next.js",
// };

interface IParams {
  params: { id: string };
}

// Dynamic Metadata (generateMetadata())
// 메타데이터를 위해 API호출하면 캐싱되어 페이지 렌더링을 위해 호출할 때는 캐시된 응답을 받기 때문에 속도가 훨씬 빠르다.
// 한 페이지에서 중복 호출하는 것이 아님
export async function generateMetadata({ params: { id } }: IParams) {
  const movie = await getMovie(id)
  return {
    title: movie.title,
  };
}

// params:{id}는 Next에서 기본제공하는 useParams를 대체하는 기능임
// url에서 동적url을 가져옴
export default async function MovieDetailPage({ params: { id } }: IParams) {
  console.log(id);
  return (
    <div>
      <Suspense fallback={<h1>Loading...</h1>}>
        <MovieInfo id={id} />
      </Suspense>
      <Suspense fallback={<h1>Loading...</h1>}>
        <MovieVideo id={id} />
      </Suspense>
    </div>
  );
}
