import "../styles/global.css"
import { Metadata } from "next";
import Menu from "../components/Menu";

export const metadata: Metadata = {
  title: {
    template: "%s | Next.js",
    default: "Loading...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  );
}
