import Navigation from "../../components/Navigation";
export const metadata = {
  title: "About Us",
  description: "Generated by Next.js",
};


export default function AboutUs() {
  return (
    <>
      <h1>About us</h1>
    </>
  );
}
